window.galleryPieces = [
  {
    id: "large-blue-bowl",
    title: "Large blue bowl",
    category: "Bowls",
    year: "2026",
    detail: "Wheel-thrown stoneware with a deep blue glaze.",
    featured: true,
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A larger statement bowl for serving or display.",
    images: ["../images/bowls/Large_blue_bowl_1.jpeg", "../images/bowls/Large_blue_bowl_4.jpeg"],
    alt: "Large blue wheel-thrown stoneware bowl"
  },
  {
    id: "wide-blue-vase",
    title: "Wide blue vase",
    category: "Vases",
    year: "2026",
    detail: "Broad wheel-thrown vase with layered blue glaze.",
    featured: true,
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A broad vase with a calm, layered blue finish.",
    images: ["../images/vase/Large_blue_vase_1.jpeg", "../images/vase/Large_blue_vase_2.jpeg"],
    alt: "Wide blue stoneware vase"
  },
  {
    id: "bisque-shelves",
    title: "Bisque shelves",
    category: "Studio",
    year: "2026",
    detail: "A kiln load in progress before glazing.",
    images: ["../images/studio/Bisque_1.jpg", "../images/studio/bisque_2.jpg"],
    alt: "Shelves of bisque-fired pottery in the studio"
  },
  {
    id: "piggy-bank",
    title: "Piggy bank",
    category: "Experiments",
    year: "2026",
    detail: "Hand-built stoneware form, still at bisque stage.",
    images: ["../images/studio/bisque_pig.jpg"],
    alt: "Bisque-fired ceramic piggy bank"
  },
  {
    id: "first-porcelain",
    title: "First porcelain",
    category: "Experiments",
    year: "2026",
    detail: "Early porcelain tests from the studio.",
    images: ["../images/studio/bisque_porcelain.jpg"],
    alt: "Porcelain test pieces after bisque firing"
  },
  {
    id: "onion-vase",
    title: "Onion vase",
    category: "Vases",
    year: "2026",
    detail: "Rounded stoneware vase with a narrow neck.",
    images: ["../images/vase/onion_blue_1.jpeg", "../images/vase/onion_blue_2.jpeg"],
    alt: "Blue onion-shaped stoneware vase"
  },
  {
    id: "blue-vase",
    title: "Blue vase",
    category: "Vases",
    year: "2026",
    detail: "Wheel-thrown vase with blue glaze variation.",
    images: ["../images/vase/blue_vase_1.jpeg", "../images/vase/blue_vase_2.jpeg"],
    alt: "Wheel-thrown blue stoneware vase"
  },
  {
    id: "large-green-flower-vase",
    title: "Large green flower vase",
    category: "Vases",
    year: "2026",
    detail: "Large flower vase with a deep green glaze and rounded profile.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A larger vase for flowers or display.",
    images: ["../images/vase/Green_vase_3.jpeg"],
    alt: "Large handmade green flower vase"
  },
  {
    id: "white-splash-bowl",
    title: "White splash bowl",
    category: "Bowls",
    year: "2025",
    detail: "Wheel-thrown bowl with a bright white splash glaze.",
    images: ["../images/bowls/white_splash_b.jpg", "../images/bowls/white_splash_a.jpg"],
    alt: "Stoneware bowl with white splash glaze"
  },
  {
    id: "nesting-yellow-bowls",
    title: "Nesting yellow bowls",
    category: "Bowls",
    year: "2026",
    detail: "Set of two bowls with a sunset yellow interior and blue rim.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A nesting pair for serving, snacks, or table use.",
    images: ["../images/bowls/Nesting_yellow.jpeg"],
    alt: "Set of two nesting bowls with sunset yellow interiors"
  },
  {
    id: "large-salad-bowl",
    title: "Large salad bowl",
    category: "Bowls",
    year: "2026",
    detail: "Large stoneware salad bowl with a soft green exterior and pale interior.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A generous bowl for salads, serving, or a table centrepiece.",
    images: ["../images/bowls/Large_bowl_2.jpeg"],
    alt: "Large handmade stoneware salad bowl"
  },
  {
    id: "golden-bowl",
    title: "Golden bowl",
    category: "Bowls",
    year: "2025",
    detail: "Layered glaze bowl with a warm golden finish.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A warm glazed bowl for everyday use or a small centrepiece.",
    images: ["../images/bowls/bowl_4_b.jpg", "../images/bowls/bowl_4_c.jpg", "../images/bowls/bowl_4_a.jpg"],
    alt: "Golden glazed stoneware bowl"
  },
  {
    id: "bowl-collection",
    title: "Bowl collection",
    category: "Bowls",
    year: "2026",
    detail: "A group of wheel-thrown bowls with different glazes.",
    images: ["../images/bowls/bowls_2.JPG", "../images/bowls/bowls_1.JPG"],
    alt: "Collection of glazed ceramic bowls"
  },
  {
    id: "brown-teapot",
    title: "Brown teapot",
    category: "Tableware",
    year: "2026",
    detail: "Stoneware teapot finished with slip and clear glaze.",
    featured: true,
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A handmade teapot with a warm brown finish.",
    images: ["../images/teapots/teapot_1.JPG", "../images/teapots/teapot_2.JPG"],
    alt: "Brown stoneware teapot"
  },
  {
    id: "pouring-jugs",
    title: "Pouring jugs",
    category: "Tableware",
    year: "2026",
    detail: "Small pouring jugs made for the table.",
    shop: true,
    status: "Made to order",
    price: "Enquire",
    shopNote: "Small pouring jugs can be made in similar forms and glazes.",
    images: ["../images/jugs/pouring_jugs_1.JPG", "../images/jugs/pouring_jugs_2.JPG", "../images/jugs/pouring_jugs_3.JPG"],
    alt: "Small ceramic pouring jugs"
  },
  {
    id: "crackle-pouring-jugs",
    title: "Crackle pouring jugs",
    category: "Tableware",
    year: "2026",
    detail: "Set of four pouring jugs with a new crackle glaze experiment.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A small set of pouring jugs in a newly tested crackle glaze.",
    images: ["../images/jugs/Crackle_jugs.jpeg"],
    alt: "Set of four handmade pouring jugs with crackle glaze"
  },
  {
    id: "blue-plate",
    title: "Blue plate",
    category: "Tableware",
    year: "2026",
    detail: "Flat plate with a flowing blue glaze.",
    images: ["../images/Plate/plate_blue_1.JPG", "../images/Plate/plate_blue_2.JPG"],
    alt: "Blue glazed ceramic plate"
  },
  {
    id: "blue-platter",
    title: "Blue platter",
    category: "Tableware",
    year: "2026",
    detail: "Large platter with a pooled blue glaze.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A larger serving piece with blue glaze movement.",
    images: ["../images/Plate/platter_blue_1.JPG", "../images/Plate/platter_blue_2.JPG"],
    alt: "Large blue glazed ceramic platter"
  },
  {
    id: "comfort-mug",
    title: "Comfort mug",
    category: "Mugs",
    year: "2025",
    detail: "Everyday mug with iron glaze.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "An everyday mug with a comfortable handle and iron glaze.",
    images: ["../images/mugs/coffee_green_a.jpeg", "../images/mugs/coffee_green_b.jpeg", "../images/mugs/coffee_green_c.jpeg"],
    alt: "Green ceramic comfort mug"
  },
  {
    id: "mosaic-cups",
    title: "Mosaic cups",
    category: "Mugs",
    year: "2026",
    detail: "A family of cups with mosaic surface decoration.",
    featured: true,
    shop: true,
    status: "Made to order",
    price: "Enquire",
    shopNote: "Available as a made-to-order set in similar colours.",
    images: ["../images/mugs/Mosaic_cups.JPG", "../images/mugs/mosaic_cup_1.JPG", "../images/mugs/mosaic_cup_2.JPG", "../images/mugs/mosaic_cup_3.JPG"],
    alt: "Mosaic patterned ceramic cups"
  },
  {
    id: "garlic-grater",
    title: "Garlic grater",
    category: "Tableware",
    year: "2025",
    detail: "Speckled clay kitchen piece with a hand-cut surface.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A practical kitchen piece in speckled clay.",
    images: ["../images/garlic/garlic_white_a.jpg", "../images/garlic/garlic_white_b.jpg"],
    alt: "White ceramic garlic grater"
  },
  {
    id: "soap-dish",
    title: "Soap dish",
    category: "Tableware",
    year: "2025",
    detail: "Carved soap dish in green glaze.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A carved dish for soap or small bathroom objects.",
    images: ["../images/soap/soap_green_a.jpeg", "../images/soap/soap_green_b.jpeg"],
    alt: "Green carved ceramic soap dish"
  },
  {
    id: "sushi-set",
    title: "Sushi set",
    category: "Tableware",
    year: "2025",
    detail: "Table pieces shaped for serving sushi.",
    images: ["../images/kitchen/sushi_a.jpg", "../images/kitchen/sushi_b.jpg"],
    alt: "Ceramic sushi serving set"
  },
  {
    id: "birdhouse-square-base",
    title: "Birdhouse, square base",
    category: "Garden",
    year: "2025",
    detail: "Hand-built birdhouse with slip and clear glaze.",
    images: ["../images/bird_house/bird_house_2_a.jpg", "../images/bird_house/bird_house_2_b.jpg", "../images/bird_house/bird_house_2_c.jpg"],
    alt: "Ceramic birdhouse with square base"
  },
  {
    id: "birdhouse-round-base",
    title: "Birdhouse, round base",
    category: "Garden",
    year: "2025",
    detail: "Round-based birdhouse made for the garden.",
    images: ["../images/bird_house/bird_house_1_a.jpg", "../images/bird_house/bird_house_1_b.jpg", "../images/bird_house/bird_house_3_a.jpg"],
    alt: "Ceramic birdhouse with round base"
  },
  {
    id: "vegetable-labels",
    title: "Vegetable labels",
    category: "Garden",
    year: "2025",
    detail: "Handmade labels for vegetables and garden beds.",
    shop: true,
    status: "Made to order",
    price: "Enquire",
    shopNote: "Garden labels can be made to order for herbs, vegetables, or beds.",
    images: ["../images/garden/veg_lables_a.jpeg", "../images/garden/veg_lables_b.jpeg"],
    alt: "Ceramic vegetable labels for a garden"
  },
  {
    id: "ring-dish",
    title: "Ring dish",
    category: "Tableware",
    year: "2025",
    detail: "Small dish for rings and jewellery.",
    images: ["../images/jewlery/jewlery_bowl_black_a.jpg", "../images/jewlery/jewlery_bowl_black_b.jpg"],
    alt: "Small black ceramic ring dish"
  },
  {
    id: "ring-box",
    title: "Ring box",
    category: "Experiments",
    year: "2025",
    detail: "Closed-form ring box with fitted lid.",
    images: ["../images/jewlery/ring_box_a.jpg", "../images/jewlery/ring_box_b.jpg"],
    alt: "Ceramic ring box with fitted lid"
  },
  {
    id: "flower-coaster",
    title: "Flower coaster",
    category: "Tableware",
    year: "2025",
    detail: "Hand-painted coaster with floral detail.",
    shop: true,
    status: "Available",
    price: "Enquire",
    shopNote: "A small hand-painted table piece.",
    images: ["../images/coaster/coaster_rose_a.jpg", "../images/coaster/coaster_flower_b.jpg"],
    alt: "Hand-painted ceramic flower coaster"
  },
  {
    id: "mobius-form",
    title: "Mobius form",
    category: "Experiments",
    year: "2025",
    detail: "Mathematical form test in clay.",
    images: ["../images/maths/mobius_a.jpeg", "../images/maths/mobius_b.jpeg"],
    alt: "Ceramic Mobius strip form"
  },
  {
    id: "kiln-opening",
    title: "Kiln opening",
    category: "Studio",
    year: "2026",
    detail: "Fresh work cooling in the kiln.",
    images: ["../images/studio/kiln_open.jpg", "../images/studio/kiln.jpg"],
    alt: "Open pottery kiln with ceramic pieces inside"
  }
];
